# These are supported funding model platforms

#github:  [softbalanced]
patreon:  softbalanced
#open_collective: # Replace with a single Open Collective username
#ko_fi: # Replace with a single Ko-fi username
#tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
#community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
#liberapay: # Replace with a single Liberapay username
#issuehunt: # Replace with a single IssueHunt username
#otechie: # Replace with a single Otechie username
#lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom:  [
'https://www.bscscan.com/address/0x1d0EF16028106207A442A9Cf8cAC139cE78B32ed',
'https://polygonscan.com/address/0x864c8fcFc3bD9e88602b543d0af41ad25063B3ef',
'https://tronscan.org/#/address/TFLTooHtkQLYnQjpd1mvXtZV3HZRZwPdr5',
'https://wavesblockexplorer.com/address/3PPGPFGmRg3P2PL9wWJB6xorSdA2pC7JJrW/assets'
]
